### ISSUE TITLE
The autocomplete panel is blinking

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#29] opened 2019-04-03 09:36 UTC
1. http://localhost:8125/ckeditor5-mention/tests/manual/mention-custom-renderer.html
1. Press "@r" and continue typing "obin".

Expected: the panel stays in the same place and does not change at all.

Actual: the panel blinks.

It happens only from time to time, so it's not a problem itself that it blinks. It's rather an indication that on every key press we do something with the panel that we shouldn't need to do.

**Comment by mlewand** [comment] 2019-04-19 10:54
Just tried to reproduce this and I'm unable to repro it on 7879d5c.

Tried Chrome, Firefox, Edge with on my machine no luck. Checked also with some low spec macbook air and it also doesn't blink there.

Might that it was reported back when the entire dropdown was moving alongside the caret or simply it got fixed down the line.

@Reinmar @Mgsy can you reproduce the issue?

[ckeditor5-mention#29.zip](https://github.com/ckeditor/ckeditor5-mention/files/3097863/ckeditor5-mention.29.zip)

**Comment by jodator** [comment] 2019-04-19 11:06
It might be also fixed by #60. (I didn't check that though).

**Comment by Mgsy** [comment] 2019-04-19 12:32
>@Reinmar @Mgsy can you reproduce the issue?

I've just checked it and can't reproduce it.

**Closed** 2019-04-19 13:49 UTC
Labels: resolution:solved, status:discussion, type:bug
